version: '3.7'
services:
#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_DATABASE: db
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: password
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    ports:
      - "8080:8080"
    #      - "2345:2345"
    depends_on:
      - db
    command: ["bash", "-c", "./wait-for-it.sh -t 1 db:5432 -- go run src/app/llmc.go"]
    #    security_opt:
    #      - "seccomp:unconfined"
    #command: /go/bin/dlv debug ./src/app --headless --log --listen=:2345 --api-version=2
    #entrypoint: dlv debug app -l 0.0.0.0:2345 --headless=true --log=true -- server
    #network_mode: "host"